# Species Classifier Configuration

# Data settings
data:
  root_dir: "data/processed/images"
  metadata_file: "data/processed/metadata.json"
  img_size: 224
  batch_size: 16
  num_workers: 4

# Model settings
model:
  name: "vit_b_16"  # Options: vit_b_16, vit_b_32, swin_t
  pretrained: true
  freeze_backbone: false
  dropout_rate: 0.1
  use_hierarchical: true  # Use hierarchical classification (family→genus→species)

# Training settings
training:
  learning_rate: 5.0e-5
  weight_decay: 1.0e-4
  optimizer: "adamw"  # Options: adam, sgd, adamw
  scheduler: "cosine"  # Options: step, cosine, plateau, none
  epochs: 50
  early_stopping_patience: 10
  gradient_accumulation_steps: 2
  mixed_precision: true
  layer_decay: 0.75  # Layer-wise learning rate decay
  progressive_resizing: [160, 224]  # Progressive image size training

# Augmentation settings
augmentation:
  horizontal_flip: true
  vertical_flip: true
  color_jitter: 0.1
  random_rotation: 10
  mixup_alpha: 0.4
  cutmix_alpha: 1.0

# Paths
paths:
  checkpoint_dir: "models/species/checkpoints"
  log_dir: "logs/species"

# Experiment tracking
experiment:
  name: "species_classifier"
  tags: ["slug", "species", "transformer"]
